### ISSUE TITLE
Suggestion: Make it easier to switch between tabs

### ISSUE THREAD

**Issue by Freeplayg** [sonnyp/gigagram#278]
A couple ideas:
- An option to show an icon-only sidebar for the list of tabs
- Allow pinning other tabs to the top bar

I do know there's already ctrl+tab, although it can be a little confusing when I'm not able to see immediately what's next or before

**Comment by wallieee** [comment]
+1 :thumbsup:

I second this. Having a sidebar for tabs does indeed make navigation so much more convenient.

I used to use Ferdium before moving into Tangram, but I eventually stopped using Ferdium because it was based on Electron and it was quite bloated. However, one feature I miss from Ferdium is this vertical sidebar with the option to set custom icons for each tab. I would love to see this feature implemented in Tangram. :heart:

Thank you to the developer and all the contributors for their hard work on this project! :clap:

**Comment by wapsi** [comment]
I second this. Now you must click first the Tangram button in the titlebar, and then the tab you want to open. It would be better UX if you can click the tab directly from tab bar (vertical or horizontal), which lists all the configured apps/tabs, like normal web browser.

**Comment by sonnyp** [comment]
https://github.com/sonnyp/Tangram/commit/346e4949e3cf82cd1938173352e1685fb97ab4be
